[defaults]
project_name="the-project"
project_description="cool project"
project_main=true
insider_only=false
use_mkdocs=false

[output."ctt/test-pytest"]
_post_tasks=[
    "uvx hatch run test",
    "uvx hatch build",
]


[output."ctt/insider_only"]
insider_only=true
